// src/lib/components/dice.svelte
<script lang="ts">
	interface Props {
		value: number;
		onClick: (() => void) | undefined;
		disabled?: boolean;
		selected?: boolean;
	}

	let { value, onClick, disabled = false, selected = false }: Props = $props();
</script>

<button
	class="relative m-auto aspect-square h-full w-full max-w-[60px] rounded-[15%] border bg-gray-50"
	onclick={onClick}
	{disabled}
>
	<svg
		width="100%"
		height="100%"
		viewBox="0 0 64 64"
		xmlns="http://www.w3.org/2000/svg"
		fill="currentColor"
	>
		{#if value % 2 === 1}
			<circle cx="32" cy="32" r="5" />
		{/if}

		{#if value > 1}
			<circle cx="48" cy="16" r="5" />
			<circle cx="16" cy="48" r="5" />
		{/if}

		{#if value > 3}
			<circle cx="16" cy="16" r="5" />
			<circle cx="48" cy="48" r="5" />
		{/if}

		{#if value === 6}
			<circle cx="32" cy="16" r="5" />
			<circle cx="32" cy="48" r="5" />
		{/if}
	</svg>

	{#if selected}
		<div class="absolute inset-0 rounded-[15%] border border-primary"></div>
	{/if}
</button>

// src/components/dice.tsx
interface DiceProps {
  num: number;
  onClick?: () => void;
  className?: string;
  disabled?: boolean;
}

export function Dice({ num, onClick, className, disabled }: DiceProps) {
  className = `m-auto relative box-content aspect-square rounded-[10%] max-w-[60px] border border-gray-300 bg-gray-50 shadow ${
    className ?? ''
  }`;

  const child =
    num < 1 ? (
      <></>
    ) : (
      <>
        {num % 2 === 1 && (
          <div className="absolute left-1/2 top-1/2 h-1/6 w-1/6 -translate-x-1/2 -translate-y-1/2 rounded-full bg-gray-500" />
        )}
        {num !== 1 && (
          <>
            <div className="absolute right-[15%] top-[15%] h-1/6 w-1/6 rounded-full bg-gray-500" />
            <div className="absolute bottom-[15%] left-[15%] h-1/6 w-1/6 rounded-full bg-gray-500" />
          </>
        )}
        {num > 3 && (
          <>
            <div className="absolute left-[15%] top-[15%] h-1/6 w-1/6 rounded-full bg-gray-500" />
            <div className="absolute bottom-[15%] right-[15%] h-1/6 w-1/6 rounded-full bg-gray-500" />
          </>
        )}
        {num === 6 && (
          <>
            <div className="absolute left-1/2 top-[15%] h-1/6 w-1/6 -translate-x-1/2 rounded-full bg-gray-500" />
            <div className="absolute bottom-[15%] left-1/2 h-1/6 w-1/6 -translate-x-1/2 rounded-full bg-gray-500" />
          </>
        )}
      </>
    );

  return onClick ? (
    <button
      onClick={onClick}
      disabled={disabled}
      className={`disabled:opacity-40 ${className}`}
    >
      {child}
    </button>
  ) : (
    <div className={className}>{child}</div>
  );
}
