// src/components/new_game.tsx
'use client';

import { useYatzyGameState } from '@/logic/game_state';
import { useState } from 'react';

export default function NewGame() {
  const [addPlayerValue, setAddPlayerValue] = useState<string>('');
  const [players, setPlayers] = useState<string[]>(['Jakob', 'Ana']);

  function addPlayer(): void {
    if (!addPlayerValue) return;
    setAddPlayerValue('');
    setPlayers([...players, addPlayerValue]);
  }

  const createGame = useYatzyGameState((s) => s.createGame);

  return (
    <div className="flex flex-col gap-5 rounded-md bg-white p-6 shadow-md">
      <h1 className="text-3xl font-medium">New game</h1>

      <div className="flex flex-col gap-1">
        <div className="text-center">Add player</div>
        <div className="flex gap-2">
          <input
            className="flex-1 rounded-md border p-2"
            type="text"
            onChange={(e) => setAddPlayerValue(e.target.value)}
            value={addPlayerValue}
            onKeyDown={(e) => {
              if (e.key == 'Enter') addPlayer();
            }}
          />
          <button className="button text-lg leading-3" onClick={addPlayer}>
            +
          </button>
        </div>
      </div>

      <div className="flex flex-col gap-1">
        <div className="text-center">Players</div>
        <div className="flex flex-col gap-2">
          {players.map((player, i) => (
            <div
              key={player}
              className="flex flex-row items-center gap-2 rounded bg-gray-100 px-4 py-2"
            >
              {/* <span>#</span> */}
              <span className="flex-1">{player}</span>
              <button
                onClick={() => {
                  const nPlayers = [...players];
                  nPlayers.splice(i, 1);
                  setPlayers(nPlayers);
                }}
                className="h-8 w-8 rounded-full bg-transparent leading-3 text-gray-500 hover:bg-gray-200"
              >
                X
              </button>
            </div>
          ))}
        </div>
      </div>

      {players.length > 0 && (
        <div className="flex flex-row justify-end gap-2">
          <button className="button" onClick={() => setPlayers([])}>
            Clear
          </button>
          <button className="button" onClick={() => createGame(players)}>
            Start
          </button>
        </div>
      )}
    </div>
  );
}

// src/routes/new-game/+page.svelte
<script lang="ts">
	import { createGame } from '$lib/game-state';
	import { faAdd, faClose } from '@fortawesome/free-solid-svg-icons';
	import Fa from 'svelte-fa';

	export let players: string[] = ['Jakob', 'Ana'];
	export let addPlayerValue: string = '';

	function addPlayer(): void {
		if (!addPlayerValue) return;
		players = [...players, addPlayerValue];
		addPlayerValue = '';
	}
</script>

<div class="card mx-auto flex max-w-xl flex-col gap-5 bg-white p-6">
	<h1 class="text-3xl font-medium">New game</h1>

	<div class="flex flex-col gap-1">
		<div class="text-center">Add player</div>
		<div class="flex gap-2">
			<input
				class="input input-bordered w-full flex-1"
				type="text"
				bind:value={addPlayerValue}
				on:keydown={(e) => {
					if (e.key == 'Enter') addPlayer();
				}}
			/>
			<button class="btn" on:click={addPlayer}>
				<Fa icon={faAdd} />
			</button>
		</div>
	</div>

	<div class="flex flex-col gap-1">
		<div class="text-center">Players</div>
		<div class="flex flex-col gap-2">
			{#each players as player, i}
				<div class="input flex flex-row items-center gap-2 pl-6 pr-3">
					<!-- <span>#</span> -->
					<span class="flex-1">{player}</span>
					<button
						on:click={() => {
							const nPlayers = [...players];
							nPlayers.splice(i, 1);
							players = nPlayers;
						}}
						class="btn btn-circle btn-ghost btn-sm"
					>
						<Fa icon={faClose} />
					</button>
				</div>
			{/each}
		</div>
	</div>

	{#if players.length > 0}
		<div class="flex flex-row justify-end gap-2">
			<button class="btn" on:click={() => (players = [])}>Clear</button>
			<button class="btn btn-primary" on:click={() => createGame(players)}>Start</button>
		</div>
	{/if}
</div>
